### ISSUE TITLE
[Feature] Logger

### ISSUE THREAD

**Issue by Pjiesco** [ChristopheCVB/TouchPortalPluginSDK#12]
**Is your feature request related to a problem? Please describe.**
There are a lot of logs. It would be nice if you could control them.

**Describe the solution you'd like**
Implement a Logger pattern to control the log level.

**Describe alternatives you've considered**
No other alternitive.

**Comment by ChristopheCVB** [comment]
@Pjiesco  Are you interested in making a PR for this?

**Comment by Pjiesco** [comment]
> @Pjiesco Are you interested in making a PR for this?

Yes, I will look into it.
