### ISSUE TITLE
[Feature] Dynamic state parent group

### ISSUE THREAD

**Issue by Pjiesco** [ChristopheCVB/TouchPortalPluginSDK#47]
In Touch Portal's next update a `parentGroup` field will be added to the `createState` message which allows for grouping of dynamic states. 
[documentation](https://www.touch-portal.com/api/index.php?section=dynamic-actions)

**Comment by ChristopheCVB** [comment]
I'm discussing a bit with Reinier about the usage of `parentGroup`, I'll let you know ;)
